version: '3'

services:

  app:
    build: .
    ports:
      - 8000:8000
      - 8001:8001
    volumes:
      - .:/app
    environment:
      DATABASE_URL: postgres://postgres@db/
    command: adev runserver app

  db:
    image: postgres:alpine
    ports:
      - 15432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres: