version: '3'

services:

  app:
    build: .
    ports:
      - 8000:8000
      - 8001:8001
    volumes:
      - .:/app
    environment:
      DATABASE_URL: postgres://postgres@db/
      AUTH_SALT: deadbeef
      SESSION_SECRET: sc6fmqk4LqM85Uuw7YXHO8ETP3rUuDwZIbtO7dy3-Ac=
      STATIC_ROOT_URL: http://localhost:8001/
    command: adev runserver app --static='static' --static-url=''

  db:
    image: postgres:alpine
    ports:
      - 15432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres: